/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.westpac.random.pins;


import java.util.Set;

public class RandomPinGenerator implements RandomPinGeneration {
    private static final int DEFAULT_NO_OF_PINS = 1000;
    private static final int MAX_VALUE = 9999;
    private static final int MIN_VALUE = 1000;

    @Override
    public Set<Integer> generateBatchOfUniqueRandomPins() {
        //Generates a batch of 1000 random unique pins in range 1000 ≤ r ≤ 9999
        return generateBatchOfUniqueRandomPins(MIN_VALUE, MAX_VALUE, DEFAULT_NO_OF_PINS);
    }


    @Override
    public Set<Integer> generateBatchOfUniqueRandomPins(final int minVal, final int maxVal, final int noOfPins) throws IllegalArgumentException {
        Random random = new Random();
        //Datatype HashSet is used to ignore duplicates values
        HashSet<Integer> randomPins = new HashSet<>();
        //while loop to generate and add pins to the HashMap until the size of the HashSet reaches the desired noOfPins
        while (randomPins.size() < noOfPins) {
            Integer pin = minVal + random.nextInt((maxVal - minVal) + 1);
            randomPins.add(pin);
        }
        return randomPins;
    }
}