/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.westpac.random.pins;


import java.util.Set;

public class RandomPinGenerator implements RandomPinGeneration {

    @Override
    public Set<Integer> generateBatchOfUniqueRandomPins() {
        return null;
    }


    @Override
    public Set<Integer> generateBatchOfUniqueRandomPins(final int minVal, final int maxVal, final int noOfPins) throws IllegalArgumentException {
        return null;
    }
}